// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  define(function() {
    var AbstractObject;
    return AbstractObject = (function() {
      function AbstractObject(options) {
        if (!options) {
          options = {};
        }
        Object.defineProperty(this, "parent", {
          value: options.parent || document.body,
          writable: false,
          configurable: false
        });
        this.childrens = [];
        this.needAnimation = true;
        this._setProperties(options);
      }

      AbstractObject.prototype.get = function(childName) {
        var index;
        index = this.index(childName);
        if (index === -1) {
          return false;
        }
        return this.childrens[index];
      };

      AbstractObject.prototype.remove = function(childName) {
        var index;
        index = this.index(childName);
        if (index === -1) {
          return false;
        }
        this.childrens.splice(index, 1);
        return true;
      };

      AbstractObject.prototype.rename = function(oldName, newName) {
        var index;
        index = this.index(oldName);
        if (index === -1) {
          return false;
        }
        this.childrens[index].name = newName;
        return true;
      };

      AbstractObject.prototype.index = function(childName) {
        var result;
        result = -1;
        this.childrens.some(function(child, index) {
          var flag;
          flag = child.name === childName;
          if (flag) {
            result = index;
          }
          return flag;
        });
        return result;
      };

      AbstractObject.prototype.shift = function(deltaX, deltaY) {
        if (deltaX == null) {
          deltaX = 0;
        }
        if (deltaY == null) {
          deltaY = 0;
        }
        return this.position = [deltaX + this.position[0], deltaY + this.position[1]];
      };

      AbstractObject.prototype.point = function(value1, value2) {
        if (value1 == null) {
          return [0, 0];
        }
        if (value2 != null) {
          return [this.number(value1), this.number(value2)];
        }
        if (Array.isArray(value1)) {
          return [this.number(value1[0]), this.number(value1[1])];
        } else {
          if ((value1.x != null) && (value1.y != null)) {
            return [this.number(value1.x), this.number(value1.y)];
          }
          if ((value1.width != null) && (value1.height != null)) {
            return [this.number(value1.width), this.number(value1.height)];
          }
          return [0, 0];
        }
      };

      AbstractObject.prototype.int = function(value) {
        return Math.round(this.number(value));
      };

      AbstractObject.prototype.number = function(value) {
        if (value != null) {
          return +value;
        } else {
          return 0;
        }
      };

      AbstractObject.prototype.deg2rad = function(value) {
        return this.number(value) * Math.PI / 180;
      };

      AbstractObject.prototype._setProperties = function(options) {
        var _alpha, _anchor, _center, _mask, _position, _realSize, _rotation, _scale, _shadow, _size, _visible, getSize;
        _visible = _position = _size = _realSize = _center = _anchor = _scale = _rotation = _alpha = _mask = _shadow = 0;
        Object.defineProperty(this, "visible", {
          get: function() {
            return _visible;
          },
          set: function(value) {
            _visible = value != null ? value : true;
            return this._setVisible();
          }
        });
        Object.defineProperty(this, "position", {
          get: function() {
            return _position;
          },
          set: function(value) {
            _position = this.point(value);
            return this._setPosition();
          }
        });
        Object.defineProperty(this, "size", {
          get: function() {
            return _size;
          },
          set: function(value) {
            _size = this.point(value);
            this.anchor = _anchor;
            return this._setSize();
          }
        });
        Object.defineProperty(this, "realSize", {
          get: function() {
            return _realSize;
          },
          set: function(value) {
            _realSize = this.point(value);
            this.anchor = _anchor;
            return this._setRealSize();
          }
        });
        Object.defineProperty(this, "center", {
          get: function() {
            return _center;
          },
          set: function(value) {
            var anchorX, anchorY, size;
            _center = this.point(value);
            size = getSize();
            anchorX = size[0] === 0 ? 0 : _center[0] / size[0];
            anchorY = size[1] === 0 ? 0 : _center[1] / size[1];
            _anchor = [anchorX, anchorY];
            return this._setCenter();
          }
        });
        getSize = (function(_this) {
          return function() {
            var size;
            return size = _size[0] === 0 && _size[1] === 0 ? _realSize : _size;
          };
        })(this);
        Object.defineProperty(this, "anchor", {
          get: function() {
            return _anchor;
          },
          set: function(value) {
            var size;
            _anchor = this.point(value);
            size = getSize();
            _center = [this.int(size[0] * _anchor[0]), this.int(size[1] * _anchor[1])];
            return this._setCenter();
          }
        });
        Object.defineProperty(this, "scale", {
          get: function() {
            return _scale;
          },
          set: function(value) {
            _scale = this.point(value);
            return this._setScale();
          }
        });
        Object.defineProperty(this, "rotation", {
          get: function() {
            return _rotation;
          },
          set: function(value) {
            _rotation = this.number(value);
            if (_rotation < 0) {
              _rotation = 360 + _rotation;
            }
            if (_rotation >= 360) {
              _rotation = _rotation % 360;
            }
            return this._setRotation();
          }
        });
        Object.defineProperty(this, "alpha", {
          get: function() {
            return _alpha;
          },
          set: function(value) {
            _alpha = this.number(value);
            return this._setAlpha();
          }
        });
        Object.defineProperty(this, "mask", {
          get: function() {
            return _mask;
          },
          set: function(value) {
            if ((value == null) || (!value)) {
              _mask = false;
              return;
            }
            _mask = {
              x: this.int(value.x),
              y: this.int(value.y),
              width: this.int(value.width),
              height: this.int(value.height)
            };
            return this._setMask();
          }
        });
        Object.defineProperty(this, "shadow", {
          get: function() {
            return _shadow;
          },
          set: function(value) {
            if ((value == null) || (!value)) {
              _shadow = false;
              this._setShadow();
              return;
            }
            _shadow = {
              color: value.color || "#000",
              blur: value.blur || 3,
              offsetX: this.int(value.offsetX),
              offsetY: this.int(value.offsetY),
              offset: this.int(value.offset)
            };
            return this._setShadow();
          }
        });
        this.visible = options.visible != null ? options.visible : true;
        this.position = options.position;
        this.size = options.size;
        this.realSize = [0, 0];
        this.center = options.center;
        this.anchor = options.anchor;
        this.scale = options.scale || [1, 1];
        this.rotation = options.rotation;
        this.alpha = options.alpha != null ? this.number(options.alpha) : 1;
        this.mask = options.mask || false;
        return this.shadow = options.shadow || false;
      };

      AbstractObject.prototype._setVisible = function() {
        return this.needAnimation = this.visible;
      };

      AbstractObject.prototype._setPosition = function() {
        this.needAnimation = true;
        return this.position;
      };

      AbstractObject.prototype._setSize = function() {
        this.needAnimation = true;
        return this.size;
      };

      AbstractObject.prototype._setRealSize = function() {
        return this.realSize;
      };

      AbstractObject.prototype._setCenter = function() {
        this.needAnimation = true;
        return this.center;
      };

      AbstractObject.prototype._setScale = function() {
        this.needAnimation = true;
        return this.scale;
      };

      AbstractObject.prototype._setRotation = function() {
        this.needAnimation = true;
        return this.rotation;
      };

      AbstractObject.prototype._setAlpha = function() {
        if (this.alpha < 0) {
          this.alpha = 0;
        }
        if (this.alpha > 1) {
          this.alpha = 1;
        }
        this.needAnimation = true;
        return this.alpha;
      };

      AbstractObject.prototype._setMask = function() {
        this.needAnimation = true;
        return this.mask;
      };

      AbstractObject.prototype._setShadow = function() {
        this.needAnimation = true;
        return this.shadow;
      };

      return AbstractObject;

    })();
  });

}).call(this);
