// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  define(function() {
    var base;
    return base = (function() {
      function base(options) {
        this._rotation = options.rotation || 0;
        this._alpha = options.alpha || 1;
        this._sizes = this._point(options.sizes);
        this._position = this._point(options.position);
        this._center = this._point(options.center);
      }

      base.prototype._point = function(value, value2) {
        if (value == null) {
          return [0, 0];
        }
        if (value2 != null) {
          return [this._int(value), this._int(value2)];
        }
        if (Array.isArray(value)) {
          return [this._int(value[0]), this._int(value[1])];
        } else {
          if ((value.x != null) && (value.y != null)) {
            return [this._int(value.x), this._int(value.y)];
          }
          if ((value.width != null) && (value.height != null)) {
            return [this._int(value.width), this._int(value.height)];
          }
          return [0, 0];
        }
      };

      base.prototype._int = function(value) {
        return Math.round(this._value(value));
      };

      base.prototype._value = function(value) {
        if (value != null) {
          return +value;
        } else {
          return 0;
        }
      };

      return base;

    })();
  });

}).call(this);
