// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["AbstractObject"], function(AbstractObject) {
    var DisplayObject;
    return DisplayObject = (function(superClass) {
      extend(DisplayObject, superClass);

      function DisplayObject(options) {
        DisplayObject.__super__.constructor.call(this, options);
        this.name = options.name || "";
        this.type = "DisplayObject";
        if (!this.context) {
          Object.defineProperty(this, "context", {
            value: this.parent.context,
            writable: false,
            configurable: false
          });
        }
      }

      DisplayObject.prototype.testPoint = function(pointX, pointY) {
        var imageData, offsetX, offsetY, pixelData;
        offsetX = pointX - this.parent.position[0];
        offsetY = pointY - this.parent.position[1];
        if (this.type === "scene") {
          offsetX -= this.position[0];
          offsetY -= this.position[1];
        }
        imageData = this.context.getImageData(offsetX, offsetY, 1, 1);
        pixelData = imageData.data;
        if (pixelData.every == null) {
          pixelData.every = Array.prototype.every;
        }
        return !pixelData.every(function(value) {
          return value === 0;
        });
      };

      DisplayObject.prototype.testRect = function(pointX, pointY) {
        var rect;
        rect = {
          left: this.position[0] + this.parent.position[0],
          top: this.position[1] + this.parent.position[1]
        };
        rect.right = rect.left + this.size[0];
        rect.bottom = rect.top + this.size[1];
        return (pointX >= rect.left) && (pointX <= rect.right) && (pointY >= rect.top) && (pointY <= rect.bottom);
      };

      DisplayObject.prototype.animate = function() {
        if (!this.visible) {
          this.needAnimation = false;
          return;
        }
        this.context.save();
        this._deltaX = this.position[0];
        this._deltaY = this.position[1];
        if (this.shadow) {
          this.context.shadowColor = this.shadow.color;
          this.context.shadowBlur = this.shadow.blur;
          this.context.shadowOffsetX = Math.max(this.shadow.offsetX, this.shadow.offset);
          this.context.shadowOffsetY = Math.max(this.shadow.offsetY, this.shadow.offset);
        }
        if (this.rotation !== 0) {
          this.context.translate(this.center[0] + this.position[0], this.center[1] + this.position[1]);
          this.context.rotate(this.deg2rad(this.rotation));
          this._deltaX = -this.center[0];
          this._deltaY = -this.center[1];
        }
        return this.needAnimation = false;
      };

      return DisplayObject;

    })(AbstractObject);
  });

}).call(this);
