// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  define(["Scene"], function(Scene) {
    var Scenes;
    return Scenes = (function() {
      function Scenes(stage) {
        this._scenes = [];
        this._stage = stage;
        this._activeSceneName = "";
      }

      Scenes.prototype.create = function(options) {
        var scene, sceneName, setActive, stagePosition;
        sceneName = options.name || "default";
        scene = this.get(sceneName);
        if (!scene) {
          stagePosition = [this._stage.offsetLeft, this._stage.offsetTop];
          options.parentPosition = stagePosition;
          scene = new Scene(options);
          this._stage.appendChild(scene.canvas);
          this._scenes.push(scene);
        }
        setActive = options.setActive != null ? options.setActive : true;
        if (setActive) {
          this._activeSceneName = sceneName;
        }
        return scene;
      };

      return Scenes;

    })();
  });

}).call(this);
