// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["DisplayObject"], function(DisplayObject) {
    var Text;
    return Text = (function(superClass) {
      extend(Text, superClass);

      function Text(options) {
        Text.__super__.constructor.call(this, options);
        this._text = options.text || "";
        this._font = options.font || "12px Arial";
        this._fillStyle = options.fillStyle || false;
        this._strokeStyle = options.strokeStyle || false;
        this.needAnimation = true;
      }

      Text.prototype.setText = function(text) {
        this._text = text;
        return this.needAnimation = true;
      };

      Text.prototype.fillStyle = function(style) {
        this._fillStyle = style || false;
        return this.needAnimation = true;
      };

      Text.prototype.strokeStyle = function(style) {
        this._strokeStyle = style || false;
        return this.needAnimation = true;
      };

      Text.prototype.setFont = function(font) {
        this._font = font || "12px Arial";
        return this.needAnimation = true;
      };

      Text.prototype.animate = function(context) {
        Text.__super__.animate.call(this, context);
        context.font = this._font;
        if (this._fillStyle) {
          context.fillStyle = this._fillStyle;
          context.fillText(this._text, this._deltaX, this._deltaY);
        }
        if (this._strokeStyle) {
          context.strokeStyle = this._strokeStyle;
          context.strokeText(this._text, this._deltaX, this._deltaY);
        }
        context.restore();
        return this.needAnimation = false;
      };

      return Text;

    })(DisplayObject);
  });

}).call(this);
