// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["DisplayObject"], function(DisplayObject) {
    var Text;
    return Text = (function(superClass) {
      extend(Text, superClass);

      function Text(options) {
        Text.__super__.constructor.call(this, options);
        this.fontHeight = 0;
        this.textWidth = 0;
        this.setFont(options.font);
        this.fillStyle = options.fillStyle || false;
        this.strokeStyle = options.strokeStyle || false;
        this.strokeWidth = options.strokeWidth != null ? this.int(options.strokeWidth) : 1;
        this.write(options.text);
      }

      Text.prototype.setFont = function(value) {
        var font, span;
        font = value || "12px Arial";
        if (font === this.font) {
          return;
        }
        this.font = font;
        span = document.createElement("span");
        span.appendChild(document.createTextNode("height"));
        span.style.cssText = "font: " + this.font + "; white-space: nowrap; display: inline;";
        document.body.appendChild(span);
        this.fontHeight = span.offsetHeight;
        document.body.removeChild(span);
        this.parent.needAnimation = true;
        return this.font;
      };

      Text.prototype.setFillStyle = function(value) {
        var fillStyle;
        fillStyle = value || false;
        if (fillStyle === this.fillStyle) {
          return;
        }
        this.fillStyle = fillStyle;
        this.parent.needAnimation = true;
        return this.fillStyle;
      };

      Text.prototype.setStrokeStyle = function(value) {
        var strokeStyle;
        strokeStyle = value || false;
        if (strokeStyle === this.strokeStyle) {
          return;
        }
        this.strokeStyle = strokeStyle;
        this.parent.needAnimation = true;
        return this.strokeStyle;
      };

      Text.prototype.setStrokeWidth = function(value) {
        var strokeWidth;
        strokeWidth = value != null ? this.int(value) : 1;
        if (strokeWidth === this.strokeWidth) {
          return;
        }
        this.strokeWidth = strokeWidth;
        this.parent.needAnimation = true;
        return this.strokeWidth;
      };

      Text.prototype.write = function(value) {
        var context, text;
        text = value || "";
        if (text === this.text) {
          return;
        }
        this.text = text;
        context = this.parent.context;
        context.save();
        context.font = this.font;
        this.textWidth = context.measureText(this.text).width;
        context.restore();
        this.parent.needAnimation = true;
        return this.text;
      };

      Text.prototype.animate = function(context) {
        var gradient;
        Text.__super__.animate.call(this, context);
        context.font = this.font;
        context.textBaseline = "top";
        if (this.fillStyle) {
          if (Array.isArray(this.fillStyle)) {
            gradient = context.createLinearGradient(this._deltaX, this._deltaY, this._deltaX, this._deltaY + this.fontHeight);
            this.fillStyle.forEach(function(color) {
              return gradient.addColorStop(color[0], color[1]);
            });
            context.fillStyle = gradient;
          } else {
            context.fillStyle = this.fillStyle;
          }
          context.fillText(this.text, this._deltaX, this._deltaY);
        }
        if (this.strokeStyle) {
          context.strokeStyle = this.strokeStyle;
          context.lineWidth = this.strokeWidth;
          return context.strokeText(this.text, this._deltaX, this._deltaY);
        }
      };

      return Text;

    })(DisplayObject);
  });

}).call(this);
