// Generated by CoffeeScript 2.0.2
(function() {
  "use strict";
  define(["Image"], function(Image) {
    var TilingImage;
    
    // Изображение, которое замостит указанную область

    // свойства:

    //  rect:Array - прямоугольник для замастивания

    // методы:

    //  setRect(value:Array):Array - установка области
    //  animate() - попытка нарисовать объект 

    return TilingImage = class TilingImage extends Image {
      constructor(options) {
        super(options);
        
        // область замостивания по умолчанию равна размеру контекста

        // массив вида [int, int, int, int]

        this.setRect(options.rect);
      }

      
      // Установка области

      setRect(value) {
        this.rect = value || [0, 0, this.canvas.width, this.canvas.height];
        this.needAnimation = true;
        return this.rect;
      }

      animate() {
        if (!this.loaded) {
          return;
        }
        
        // если объект не видимый
        // то рисовать его не нужно

        if (!this.visible) {
          this.needAnimation = false;
          return;
        }
        
        // Начало отрисовки

        this.context.beginPath();
        
        // создаем паттерн

        this.context.fillStyle = this.context.createPattern(this.image, "repeat");
        
        // рисуем прямоугольник

        this.context.rect(this.rect[0], this.rect[1], this.rect[2], this.rect[3]);
        
        // заливаем паттерном

        this.context.fill();
        
        // анимация больше не нужна

        return this.needAnimation = false;
      }

    };
  });

}).call(this);
