// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  define(["Image"], function(Image) {
    var TilingImage;
    return TilingImage = (function(superClass) {
      extend(TilingImage, superClass);

      function TilingImage(options) {
        TilingImage.__super__.constructor.call(this, options);
        this.setRect(options.rect);
      }

      TilingImage.prototype.setRect = function(value) {
        this.rect = value || [0, 0, this.canvas.width, this.canvas.height];
        this.needAnimation = true;
        return this.rect;
      };

      TilingImage.prototype.animate = function() {
        if (!this.loaded) {
          return;
        }
        this.context.beginPath();
        this.context.fillStyle = this.context.createPattern(this.image, "repeat");
        this.context.rect(this.rect[0], this.rect[1], this.rect[2], this.rect[3]);
        return this.context.fill();
      };

      return TilingImage;

    })(Image);
  });

}).call(this);
