// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  define(function() {
    var ImagesLoader;
    return ImagesLoader = (function() {
      function ImagesLoader(path) {
        if (path == null) {
          path = "";
        }
        this.setPath(path);
      }

      ImagesLoader.prototype.setPath = function(path) {
        return this._path = path;
      };

      ImagesLoader.prototype.loadList = function(list, callBack) {
        var loaded, newList, total;
        total = list.length;
        loaded = 0;
        newList = {};
        return list.forEach((function(_this) {
          return function(image) {
            return _this.loadImage(image.src, function(result) {
              loaded++;
              // BO.generate("imageLoaded", total, loaded, result);
              newList[image.name] = {};
              newList[image.name].image = result.image;
              newList[image.name].sizes = result.sizes;
              newList[image.name].src = image.src;
              if (loaded === total) {
                // BO.generate("imagesAllLoaded", total, loaded, newList);
                if (callBack != null) {
                  return callBack(total, loaded, newList);
                }
              }
            }, function(e) {
              return log(e, "error");
            });
          };
        })(this));
      };

      ImagesLoader.prototype.loadImage = function(src, onload, onerror) {
        var image;
        image = document.createElement("img");
        image.onload = (function(_this) {
          return function() {
            if (typeof onload === "function") {
              return onload({
                image: image,
                src: _this._path + src,
                sizes: [image.width, image.height]
              });
            }
          };
        })(this);
        image.onerror = onerror;
        return image.src = this._path + src;
      };

      return ImagesLoader;

    })();
  });

}).call(this);
