// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var AnimatedArrow;
    return AnimatedArrow = (function() {
      function AnimatedArrow(options) {
        this.update = bind(this.update, this);
        this._scene = options.scene;
        if (!options.scene) {
          return;
        }
        this._graph = this._scene.add({
          type: "graph"
        });
        this._arrow = this._scene.add({
          type: "graph"
        });
        this._blockSize = options.blockSize || 50;
        this._spaceSize = options.spaceSize || 20;
        this._width = options.width || 100;
        this._style = options.style || "rgb(255, 0, 0)";
        this._offset = this._blockSize + this._spaceSize;
        this._speed = options.speed || 1;
        this._arrowWidth = Math.round(this._blockSize);
        this._arrowHeight = Math.round(this._width);
        this._from = options.from || [0, 0];
        this._to = options.to || [500, 500];
        this.setPoints(this._from, this._to);
      }

      AnimatedArrow.prototype.setPoints = function(point1, point2) {
        var dx, dy, length, newlength;
        this._from = this._scene.pixel(point1);
        this._to = this._arrowTo = this._scene.pixel(point2);
        dx = this._from[0] - this._to[0];
        dy = this._from[1] - this._to[1];
        length = Math.sqrt(dx * dx + dy * dy);
        newlength = length - this._blockSize + 2;
        if (newlength === 0) {
          newlength = 0.00001;
        }
        this._to[0] = this._from[0] - newlength * dx / length;
        this._to[1] = this._from[1] - newlength * dy / length;
        if (dx === 0) {
          dx = 0.00001;
        }
        this._angle = Math.atan(dy / dx);
        if (dx > 0) {
          this._angle += Math.PI;
        }
        this._angle /= this._scene._PIDIV180;
        return this._redraw();
      };

      AnimatedArrow.setTo = function(point) {
        return this.setPoints(this._from, point);
      };

      AnimatedArrow.setFrom = function(point) {
        return this.setPoints(point, this._to);
      };

      AnimatedArrow.prototype.update = function() {
        this._offset -= this._speed;
        if (this._offset < 0) {
          this._offset = this._blockSize + this._spaceSize;
        }
        return this._redrawLine();
      };

      AnimatedArrow.prototype._redrawLine = function() {
        this._graph.clear();
        this._graph.strokeStyle(this._style);
        this._graph.lineWidth(this._width);
        this._graph.setLineDash([this._blockSize, this._spaceSize]);
        this._graph.lineDashOffset = this._offset;
        this._graph.moveTo(this._from);
        this._graph.lineTo(this._to);
        return this._graph.stroke();
      };

      AnimatedArrow.prototype._redraw = function() {
        return this._redrawLine();

        /*@_arrow.clear()
        			@_arrow.lineWidth 1
        			@_arrow.setCenter @_arrowTo
        			@_arrow.rotate @_angle
        			@_arrow.moveTo @_arrowTo[0] - @_arrowWidth, @_arrowTo[1] - @_arrowHeight
        			@_arrow.lineTo @_arrowTo[0], @_arrowTo[1]
        			@_arrow.lineTo @_arrowTo[0] - @_arrowWidth, @_arrowTo[1] + @_arrowHeight
        			@_arrow.lineTo @_arrowTo[0] - @_arrowWidth, @_arrowTo[1] - @_arrowHeight
        			@_arrow.fillStyle @_style
        			@_arrow.fill()
         */
      };

      return AnimatedArrow;

    })();
  });

}).call(this);
